import "./globals.css";



export const metadata = {
  title: "Parth Institute - SPREADING KNOWLEDGE...",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="LTR">
      <body >{children}</body>
    </html>
  );
}
