import "./globals.css";

export const metadata = {
  title: "Parth Institute - SPREADING KNOWLEDGE...",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="LTR">
     
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link id="favicon" rel="icon" href="/images/pi.ico" />
        
      <body>{children}</body>
    </html>
  );
}
